# -*- coding: utf-8 -*-
"""Copia de json_total

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13h4xAC6-MUsMFB9QwLlG-Fn3-0TJmmBI
"""

import json
import pandas as pd
from google.colab import files

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/json/openalexco.json','r') as miarchivo:
    objeto=miarchivo.read()
objeto=json.loads(objeto)

ob=objeto[0]
ob

def filter_concept(concepts,concept='Physics'):
    return any([True for c in concepts if c.get('display_name')==concept])

objeto   = [d for d in objeto if (filter_concept(d.get('concepts'),concept='Astronomy')or 
                           filter_concept(d.get('concepts'),concept='Astrophysics') or  filter_concept(d.get('concepts'),concept='Quantum mechanics')) ]                         
objeto

def filter_ror(authorships,ror="https://ror.org/03bp5hc83"):
  return any([any([i.get('ror')=="https://ror.org/03bp5hc83" for i in a.get('institutions')])  for a in authorships])

ph_udea     = [d for d in objeto    if filter_ror(d.get('authorships'),ror="https://ror.org/03bp5hc83")]

ph_udea

len(ph_udea)

import pandas as pd

df=pd.DataFrame(ph_udea)
df

js = df.to_json('/content/drive/MyDrive/json/OpenAlex Cosmology.json', orient = 'columns')